version: '3'

services:
  redis:
    image: redis
  web:
    build: .
    depends_on:
      - redis
  loadbalancer:
    image:  dockercloud/haproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - web
    ports:
      - 8080:80